### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by mlposey** [butteredwaffles/tropebrowser#1]
@butteredwaffles  I saw your work on the animal crossing hybrid breeder. Are you still interested in front-end development? I have a project I would like to work on soon and am looking for someone to develop the user interface. This will be paid work.

**Comment by butteredwaffles** [comment]
Hi, been a while! Sorry, but I don't really feel confident enough in my front-end abilities.

**Comment by mlposey** [comment]
Ah, okay. No worries. I hope all is well!
